### ISSUE TITLE
Peer review

### ISSUE THREAD

**Issue by juhkure** [ismomehdi/FIFO-App-for-Crypto#1]
First time loading the transactions page gave an error. I couldn't replicate it so not sure what was the cause. Anyways...

Unless it's something that would overly complicate otherwise simple future functions, having an extra column in transactions table to differentiate sells and buys from each other would in my opinion be worth it just for the sake of being more explicit. And I would argue it could save you a lot of future headaches with database queries.

Another idea would be to just to split them into their own separate tables entirely. Maybe even a relation that ties a specific first out sell order with a specific first in buy order if that's any use for upcoming features.

And with the project being in it's early stages, it's difficult to see the direction you're going for with the code structure but I know personally that having a schema that's few steps ahead of your current features can help a lot with regard to code design/structure decisions. It's like a plan but a part of the application!

Good going!

**Comment by ismomehdi** [comment]
Thanks for the feedback!
